export const songs = [
  {
    id: "somewhere-only-we-know",
    title: "Somewhere Only We Know",
    artist: "Gustixa, rihanne",
    language: "english",
    artwork: import.meta.env.BASE_URL + "images/Gemini_Generated_Image_ (1).png", 
    audioSrc: import.meta.env.BASE_URL + "audio/Keane - Somewhere Only We Know (Lyrics).mp3",
    themeId: "forest",
    category: "Chill",
    duration: "6:12",
  },
  {
    id: "until-i-found-you",
    title: "Until I Found You",
    artist: "Stephen Sanchez",
    language: "english",
    artwork: import.meta.env.BASE_URL + "images/Gemini_Generated_Image_5a9q205a9q205a9q.png",
    audioSrc: import.meta.env.BASE_URL + "audio/Stephen Sanchez - Until I Found You (Official Video).mp3",
    themeId: "sunset",
    category: "Romantic",
    duration: "7:05",
  },
  {
    id: "night-changes",
    title: "Night Changes",
    artist: "One Direction",
    language: "english",
    artwork: import.meta.env.BASE_URL + "images/Gemini_Generated_Image_dde27cdde27cdde2.png", 
    audioSrc: import.meta.env.BASE_URL + "audio/One Direction - Night Changes.mp3",
    themeId: "night",
    category: "Late Night",
    duration: "5:44",
  },
  {
    id: "blue",
    title: "blue",
    artist: "yung kai",
    language: "english",
    artwork: import.meta.env.BASE_URL + "images/Gemini_Generated_Image_p82yhop82yhop82y.png",
    audioSrc: import.meta.env.BASE_URL + "audio/yung kai - blue (official music video).mp3",
    themeId: "blue",
    category: "Sad",
    duration: "5:02",
  },
  {
    id: "dandelions",
    title: "Dandelions",
    artist: "Ruth B.",
    language: "english",
    artwork: import.meta.env.BASE_URL + "images/Gemini_Generated_Image_rk3u2crk3u2crk3u.png", 
    audioSrc: import.meta.env.BASE_URL + "audio/Ruth B. - Dandelions (Lyrics).mp3",
    themeId: "forest",
    category: "Romantic",
    duration: "5:53",
  },
  {
    id: "line-without-a-hook",
    title: "Line Without a Hook",
    artist: "Ricky Montgomery",
    language: "english",
    artwork: import.meta.env.BASE_URL + "images/Gemini_Generated_Image_swaug0swaug0swau.png",
    audioSrc: import.meta.env.BASE_URL + "audio/Ricky Montgomery - Line Without a Hook (Official Lyric Video).mp3",
    themeId: "blue",
    category: "Sad",
    duration: "6:08",
  },
  {
    id: "co2",
    title: "Co2",
    artist: "Prateek Kuhad",
    language: "hindi",
    artwork: import.meta.env.BASE_URL + "images/Gemini_Generated_Image_v1zjjkv1zjjkv1zj.png",
    audioSrc: import.meta.env.BASE_URL + "audio/Prateek Kuhad - Co2 (Official Audio).mp3",
    themeId: "sunset",
    category: "Chill",
    duration: "5:11",
  },
  {
    id: "ordinary",
    title: "Ordinary",
    artist: "Alex Warren",
    language: "english",
    artwork: import.meta.env.BASE_URL + "images/Gemini_Generated_Image_wz2371wz2371wz23.png",
    audioSrc: import.meta.env.BASE_URL + "audio/Alex Warren - Ordinary (Lyrics).mp3",
    themeId: "night",
    category: "Sad",
    duration: "5:26",
  },
  {
    id: "i-think-they-call-this-love",
    title: "I Think They Call This Love - Cover",
    artist: "Matthew Ifield",
    language: "english",
    artwork: import.meta.env.BASE_URL + "images/Gemini_Generated_Image_xsj6v5xsj6v5xsj6.png",
    audioSrc: import.meta.env.BASE_URL + "audio/I Think They Call This Love (Cover).mp3",
    themeId: "forest",
    category: "Romantic",
    duration: "6:20",
  },
  {
    id: "until-i-found-you-em",
    title: "Until I Found You (with Em Beihold)",
    artist: "Stephen Sanchez, Em Beihold",
    language: "english",
    artwork: import.meta.env.BASE_URL + "images/Gemini_Generated_Image_ (1).png",
    audioSrc: import.meta.env.BASE_URL + "audio/Stephen Sanchez - Until I Found You (Official Video) (1).mp3",
    themeId: "sunset",
    category: "Romantic",
    duration: "6:25",
  },
  {
    id: "perfect",
    title: "Perfect",
    artist: "Ed Sheeran",
    language: "english",
    artwork: import.meta.env.BASE_URL + "images/Gemini_Generated_Image_5a9q205a9q205a9q.png",
    audioSrc: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-11.mp3",
    themeId: "night",
    category: "Romantic",
    duration: "7:02",
  },
  {
    id: "a-thousand-years",
    title: "a thousand years",
    artist: "Christina Perri",
    language: "english",
    artwork: import.meta.env.BASE_URL + "images/Gemini_Generated_Image_dde27cdde27cdde2.png",
    audioSrc: import.meta.env.BASE_URL + "audio/Christina Perri - A Thousand Years (Lyrics).mp3",
    themeId: "blue",
    category: "Late Night",
    duration: "6:13",
  },
  {
    id: "tum-se-hi",
    title: "Tum Se Hi",
    artist: "Mohit Chauhan",
    language: "hindi",
    artwork: import.meta.env.BASE_URL + "images/Gemini_Generated_Image_p82yhop82yhop82y.png",
    audioSrc: import.meta.env.BASE_URL + "audio/Tum Se Hi Lyrcial  Jab We Met  Kareena Kapoor, Shahid Kapoor  Mohit Chauhan  Pritam.mp3",
    themeId: "forest",
    category: "Romantic",
    duration: "5:21",
  },
  {
    id: "aaoge-tum-kabhi",
    title: "Aaoge Tum Kabhi",
    artist: "The Local Train",
    language: "hindi",
    artwork: import.meta.env.BASE_URL + "images/Gemini_Generated_Image_rk3u2crk3u2crk3u.png",
    audioSrc: import.meta.env.BASE_URL + "audio/The Local Train - Aaoge Tum Kabhi (Official).mp3",
    themeId: "sunset",
    category: "Indie",
    duration: "5:17",
  },
  {
    id: "channa-ve",
    title: "Channa Ve",
    artist: "Akhil Sachdeva, Mansheel Gujral",
    language: "hindi",
    artwork: import.meta.env.BASE_URL + "images/Gemini_Generated_Image_swaug0swaug0swau.png",
    audioSrc: import.meta.env.BASE_URL + "audio/Channa Ve - Full Video  Bhoot - Part One_ The Haunted Ship  Vicky K & Bhumi P  Akhil & Mansheel.mp3",
    themeId: "night",
    category: "Romantic",
    duration: "3:25",
  },
  {
    id: "tum-agar-samne",
    title: "Tum Agar Samne",
    artist: "Abhijeet, Alka Yagnik",
    language: "hindi",
    artwork: import.meta.env.BASE_URL + "images/Gemini_Generated_Image_v1zjjkv1zjjkv1zj.png",
    audioSrc: import.meta.env.BASE_URL + "audio/Main Agar Saamne Song Video - Raaz  Dino Moreo & Bipasha Basu  Abhijeet & Alka Yagnik.mp3",
    themeId: "blue",
    category: "Classic",
    duration: "5:45",
  },
  {
    id: "kalank-title-track",
    title: "Kalank (Title Track)",
    artist: "Arijit Singh",
    language: "hindi",
    artwork: import.meta.env.BASE_URL + "images/Gemini_Generated_Image_wz2371wz2371wz23.png",
    audioSrc: import.meta.env.BASE_URL + "audio/Kalank Title Track - Lyrical  Alia Bhatt , Varun Dhawan  Arijit Singh  Pritam Amitabh.mp3",
    themeId: "ocean",
    category: "Romantic",
    duration: "5:11",
  },
  {
    id: "meri-kahani",
    title: "Meri Kahani",
    artist: "Atif Aslam",
    language: "hindi",
    artwork: import.meta.env.BASE_URL + "images/Gemini_Generated_Image_xsj6v5xsj6v5xsj6.png",
    audioSrc: import.meta.env.BASE_URL + "audio/Meri Kahani - Official Video  Meri Kahani  Atif Aslam  Mahmood Rahman, Sameer Shami & Farhad.mp3",
    themeId: "forest",
    category: "Nostalgia",
    duration: "3:40",
  },
  {
    id: "pehli-nazar-mein",
    title: "Pehli Nazar Mein",
    artist: "Atif Aslam",
    language: "hindi",
    artwork: import.meta.env.BASE_URL + "images/Gemini_Generated_Image_ (1).png",
    audioSrc: import.meta.env.BASE_URL + "audio/Pehli Nazar Mein Kaise Jaado Kar Diya  Atif Aslam Hits  Race I Akshaye, Bipasha & Saif Ali.mp3",
    themeId: "sunset",
    category: "Romantic",
    duration: "5:14",
  },
  {
    id: "mann-ki-lagan",
    title: "Mann Ki Lagan",
    artist: "Rahat Fateh Ali Khan",
    language: "hindi",
    artwork: import.meta.env.BASE_URL + "images/Gemini_Generated_Image_5a9q205a9q205a9q.png",
    audioSrc: import.meta.env.BASE_URL + "audio/Mann Ki Lagan  Rahat Fateh Ali Khan  Paap  Shahi  Amjad Islam Amjad  Old Hindi Song.mp3",
    themeId: "night",
    category: "Soulful",
    duration: "4:59",
  },
  {
    id: "dil-ka-jo-haal-hai",
    title: "Dil Kaa Jo Haal Hai",
    artist: "Abhijeet, Shreya Ghoshal",
    language: "hindi",
    artwork: import.meta.env.BASE_URL + "images/Gemini_Generated_Image_dde27cdde27cdde2.png",
    audioSrc: import.meta.env.BASE_URL + "audio/Dil Ka Jo Haal Hai (Lyrical)  Besharam  Ranbir Kapoor  Abhijeet Bhattacharya, Shreya Ghoshal.mp3",
    themeId: "blue",
    category: "Upbeat",
    duration: "4:43",
  },
  {
    id: "tu-chahiye",
    title: "Tu Chahiye",
    artist: "Atif Aslam",
    language: "hindi",
    artwork: import.meta.env.BASE_URL + "images/Gemini_Generated_Image_p82yhop82yhop82y.png",
    audioSrc: import.meta.env.BASE_URL + "audio/'Tu Chahiye' FULL VIDEO Song - Atif Aslam Pritam  Bajrangi Bhaijaan  Salman Khan, Kareena Kapoor.mp3",
    themeId: "forest",
    category: "Romantic",
    duration: "4:32",
  },
  {
    id: "main-rang-sharbaton-ka",
    title: "Main Rang Sharbaton Ka",
    artist: "Atif Aslam, Chinmayi",
    language: "hindi",
    artwork: import.meta.env.BASE_URL + "images/Gemini_Generated_Image_rk3u2crk3u2crk3u.png",
    audioSrc: import.meta.env.BASE_URL + "audio/Main Rang Sharbaton Ka  Arijit Singh  Phata Poster Nikhla Hero  2013.mp3",
    themeId: "sunset",
    category: "Romantic",
    duration: "4:23",
  },
  {
    id: "dil-tu-jaan-tu",
    title: "Dil Tu Jaan Tu",
    artist: "Gurnazar",
    language: "hindi",
    artwork: import.meta.env.BASE_URL + "images/Gemini_Generated_Image_swaug0swaug0swau.png",
    audioSrc: import.meta.env.BASE_URL + "audio/DIL TU JAAN TU  GURNAZAR  Kritika Yadav  New Punjabi Song  Chet Singh  Jhankar Music Punjabi.mp3",
    themeId: "night",
    category: "Romantic",
    duration: "3:20",
  },
  {
    id: "ilahi",
    title: "Ilahi",
    artist: "Arijit Singh",
    language: "hindi",
    artwork: import.meta.env.BASE_URL + "images/Gemini_Generated_Image_v1zjjkv1zjjkv1zj.png",
    audioSrc: import.meta.env.BASE_URL + "audio/Ilahi Full Video Song  Yeh Jawaani Hai Deewani  Ranbir Kapoor, Deepika Padukone  Pritam.mp3",
    themeId: "ocean",
    category: "Travel",
    duration: "3:48",
  },
  {
    id: "shayraana",
    title: "Shayraana",
    artist: "Shalmali Kholgade",
    language: "hindi",
    artwork: import.meta.env.BASE_URL + "images/Gemini_Generated_Image_wz2371wz2371wz23.png",
    audioSrc: import.meta.env.BASE_URL + "audio/Arijit Singh - Aaj Dil Shaayraana  Holiday  Akshay Kumar & Sonakshi Sinha  Pritam.mp3",
    themeId: "forest",
    category: "Upbeat",
    duration: "4:18",
  },
  {
    id: "channa-mereya",
    title: "Channa Mereya",
    artist: "Arijit Singh",
    language: "hindi",
    artwork: import.meta.env.BASE_URL + "images/Gemini_Generated_Image_xsj6v5xsj6v5xsj6.png",
    audioSrc: import.meta.env.BASE_URL + "audio/Channa Mereya - Lyric Video  Ae Dil Hai Mushkil  Karan Johar  Ranbir  Anushka  Pritam  Arijit.mp3",
    themeId: "sunset",
    category: "Sad",
    duration: "4:49",
  },
  {
    id: "banjaara",
    title: "Banjaara",
    artist: "Mohd. Irfan",
    language: "hindi",
    artwork: import.meta.env.BASE_URL + "images/Gemini_Generated_Image_ (1).png",
    audioSrc: import.meta.env.BASE_URL + "audio/Banjaara Full Video Song  Ek Villain  Shraddha Kapoor, Siddharth Malhotra.mp3",
    themeId: "night",
    category: "Sad",
    duration: "5:36",
  },
  {
    id: "kyon",
    title: "Kyon",
    artist: "Papon, Sunidhi Chauhan",
    language: "hindi",
    artwork: import.meta.env.BASE_URL + "images/Gemini_Generated_Image_5a9q205a9q205a9q.png",
    audioSrc: import.meta.env.BASE_URL + "audio/Pritam, Papon, Sunidhi Chauhan - Kyon - Lyrical Video  Ranbir, Priyanka  Barfi  Papon, Sunidhi.mp3",
    themeId: "blue",
    category: "Chill",
    duration: "4:26",
  },
  {
    id: "aashiyan",
    title: "Aashiyan",
    artist: "Shreya Ghoshal, Nikhil Paul",
    language: "hindi",
    artwork: import.meta.env.BASE_URL + "images/Gemini_Generated_Image_dde27cdde27cdde2.png",
    audioSrc: import.meta.env.BASE_URL + "audio/Aashiyan - BarfiPritamShreyaNikhil Paul GeorgeRanbirPriyanka.mp3",
    themeId: "ocean",
    category: "Happy",
    duration: "3:56",
  }
];

