export const songs = [
  {
    id: "somewhere-only-we-know",
    title: "Somewhere Only We Know",
    artist: "Gustixa, rihanne",
    artwork: "/images/1.jpg", 
    audioSrc: "/audio/Keane - Somewhere Only We Know (Lyrics).mp3",
    themeId: "forest",
    category: "Chill",
    duration: "6:12",
  },
  {
    id: "until-i-found-you",
    title: "Until I Found You",
    artist: "Stephen Sanchez",
    artwork: "/images/2.jpg",
    audioSrc: "/audio/Stephen Sanchez - Until I Found You (Official Video).mp3",
    themeId: "sunset",
    category: "Romantic",
    duration: "7:05",
  },
  {
    id: "night-changes",
    title: "Night Changes",
    artist: "One Direction",
    artwork: "/images/3.jpg", 
    audioSrc: "/audio/One Direction - Night Changes.mp3",
    themeId: "night",
    category: "Late Night",
    duration: "5:44",
  },
  {
    id: "blue",
    title: "blue",
    artist: "yung kai",
    artwork: "/images/4.jpg",
    audioSrc: "/audio/yung kai - blue (official music video).mp3",
    themeId: "blue",
    category: "Sad",
    duration: "5:02",
  },
  {
    id: "dandelions",
    title: "Dandelions",
    artist: "Ruth B.",
    artwork: "/images/1.jpg", 
    audioSrc: "/audio/Ruth B. - Dandelions (Lyrics).mp3",
    themeId: "forest",
    category: "Romantic",
    duration: "5:53",
  },
  {
    id: "line-without-a-hook",
    title: "Line Without a Hook",
    artist: "Ricky Montgomery",
    artwork: "/images/4.jpg",
    audioSrc: "/audio/Ricky Montgomery - Line Without a Hook (Official Lyric Video).mp3",
    themeId: "blue",
    category: "Sad",
    duration: "6:08",
  },
  {
    id: "co2",
    title: "Co2",
    artist: "Prateek Kuhad",
    artwork: "/images/2.jpg",
    audioSrc: "/audio/Prateek Kuhad - Co2 (Official Audio).mp3",
    themeId: "sunset",
    category: "Chill",
    duration: "5:11",
  },
  {
    id: "ordinary",
    title: "Ordinary",
    artist: "Alex Warren",
    artwork: "/images/3.jpg",
    audioSrc: "/audio/Alex Warren - Ordinary (Lyrics).mp3",
    themeId: "night",
    category: "Sad",
    duration: "5:26",
  },
  {
    id: "i-think-they-call-this-love",
    title: "I Think They Call This Love - Cover",
    artist: "Matthew Ifield",
    artwork: "/images/1.jpg",
    audioSrc: "/audio/I Think They Call This Love (Cover).mp3",
    themeId: "forest",
    category: "Romantic",
    duration: "6:20",
  },
  {
    id: "until-i-found-you-em",
    title: "Until I Found You (with Em Beihold)",
    artist: "Stephen Sanchez, Em Beihold",
    artwork: "/images/2.jpg",
    audioSrc: "/audio/Stephen Sanchez - Until I Found You (Official Video) (1).mp3",
    themeId: "sunset",
    category: "Romantic",
    duration: "6:25",
  },
  {
    id: "perfect",
    title: "Perfect",
    artist: "Ed Sheeran",
    artwork: "/images/3.jpg",
    audioSrc: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-11.mp3",
    themeId: "night",
    category: "Romantic",
    duration: "7:02",
  },
  {
    id: "a-thousand-years",
    title: "a thousand years",
    artist: "Christina Perri",
    artwork: "/images/4.jpg",
    audioSrc: "/audio/Christina Perri - A Thousand Years (Lyrics).mp3",
    themeId: "blue",
    category: "Late Night",
    duration: "6:13",
  }
];
